baseURL: 'https://nsorros.github.io'
languageCode: en-us
title: Nick Sorros
theme: PaperMod

googleAnalytics: G-SGMTPX0KNQ

menu:
    main:
        - identifier: about
          name: about
          url: /about/
          weight: 10
        - identifier: talks
          name: talks
          url: /tags/talk/
          weight: 20
        - identifier: tags
          name: tags
          url: /tags/
          weight: 30

params:
    ShowCodeCopyButtons: true
    ShowPostNavLinks: true
    ShowReadingTime: true
    ShowBreadCrumbs: true

    homeInfoParams:
        Title: "Hi 👋"
        Content: >
            My name is Nick Sorros and I am a Data Scientist specialising in Natural Language Processing.
            I am also the founder of [MantisNLP](https://mantisnlp.com/) ✨, a remote first NLP consultancy. If you are interested to work
            with me, drop me an email at nick@mantisnlp.com
        
    socialIcons:
        - name: twitter
          url: "https://twitter.com/nsorros"
        - name: github
          url: "http://github.com/nsorros"
        - name: linkedin
          url: "https://www.linkedin.com/in/nsorros/"