baseURL = 'https://nsorros.github.io'
languageCode = 'en-us'
title = 'Nick Sorros'
theme = 'PaperMod'

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "talks"
name = "talks"
url = "/tags/talk/"
weight = 20

[params.homeInfoParams]
Title = "Hi 👋"
Content = """
    my name is Nick Sorros and i am a Data Scientist
    i am also the founder of MantisNLP

    i co organise the PyData meetup in Cyprus
    and i also participate in the scoping commitee of DataKind UK
"""

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/nsorros"

[[params.socialIcons]]
name = "github"
url = "http://github.com/nsorros"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/nsorros/"

[[params.socialIcons]]
name = "email"
url = "mailto:nick@mantisnlp.com"

[params]
ShowCodeCopyButtons = "true"
ShowPostNavLinks = "true"
ShowReadingTime = "true"
ShowBreadCrumbs = "true"